name: 'Create Deployment Record'
description: 'Registra o deployment na API do GitHub'

inputs:
  environment:
    description: 'Ambiente do deployment'
    required: true
  build_number:
    description: 'Número do build'
    required: true
  artifact_name:
    description: 'Nome do artefato'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Register deployment
      shell: bash
      run: |
        echo "📊 Registrando deployment..."
        
        BUILD_NUMBER="${{ inputs.build_number }}"
        VERSION="${{ inputs.artifact_name }}"
        
        # Cria deployment no GitHub (aparece na aba Environments)
        DEPLOYMENT=$(curl -s -X POST \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/deployments" \
          -d "{
            \"ref\": \"master\",
            \"environment\": \"${{ inputs.environment }}\",
            \"description\": \"Deploy Build #$BUILD_NUMBER ($VERSION) to ${{ inputs.environment }}\",
            \"auto_merge\": false,
            \"required_contexts\": []
          }")
        
        DEPLOYMENT_ID=$(echo "$DEPLOYMENT" | jq -r '.id')
        
        # Marca deployment como sucesso
        curl -s -X POST \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses" \
          -d "{
            \"state\": \"success\",
            \"description\": \"Build #$BUILD_NUMBER deployed successfully\",
            \"environment_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }"
        
        echo "✅ Deployment registrado (ID: $DEPLOYMENT_ID)"
        echo "📍 Veja em: https://github.com/${{ github.repository }}/deployments"
